---
title: "Version history"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## v.1.2.1.0000#rats 
#### 2022/08/06
#### **NOTE: This version is the one used for the IM+sync paper Kleinbub et al., 2023**

  * ~~rats are almost stable


## v.1.2.0.9002
#### 2022/12/01
#### **WARNING: This version is not yet tested**
  * renamed all R files lol
  * removed DyadStream
  * all dyadstream and ts objects have been replaced by ~~rats! uwu
  * all @TSBUG errors should have been fixed.
    * These elements where searched: @TSBUG tss tse xstart xend tsp ts start end startend sampRate(  DyadStream    
  * categoriesPermutation
    *   has been given parallelization treatment, better plot, and now can export the data
    *   results are now saved in a returned object
    *   plot has been improved
    *   the padding between random windows is now more random.
  * all mentions of "streams" have been replaced by "series". Notably in the functions epochStream, extractEpochs, categoryPerm

## v.1.2.0.9001
#### 2022/12/01
#### **WARNING: This version is not going to be backward compatible with most scripts!**
  * peakFinder \$seconds renamed to \$time
  * peakFinder \$type renamed to \$class
  * DyadSignal now maintains attributes of dyad session group ids
  * AMICo v2 RC 0.4 is 
  * removed possibility of running sync analyses on multiple signals, as each signal
    requires ad hoc settings.
  * ccfBest now is parallelized
  * metadata (es:groupId) are now saved also in child objects, such as dyadSignals

## v.1.1.0
#### 2022/11/23
  * merged dev4 branch and generally stable version

## v.1.0.0.9024
#### 2022/11/23
  * renamed groupIndex to categoryIndex and streamKey to stream
  * renamed PMbest to AMICo
  * parallelized AMICo
  * general clean up and obsolescence file

## v.1.0.0.9023
#### 2022/09/20
  * switched to data.table for input output tasks
  * started parallelization of the package (signalFilter)
  
## v.1.0.0.9022
#### 2022/09/20
  * vastly improved fadein fadeout performance in FIR. Note to self. This approach could be used in other filters too.
  * vastly improved c.DyadExperiment
  * minor fixes to readCategories()
  * new extraction method for DyadExperiment objects
  * implemented "[.DyadExperiment" to extract or replace parts of a DyadExperiment

## v.1.0.0.9021
#### 2021/12/17
  * lowpass() was substituted by FIR()

## v.1.0.0.9020
#### 2021/12/01
  * pairBind had possible exceptions. it is still not 100% tested though.
  * peakFinder now always calculates peaks and valleys, performs all cleanings, and then removes either one or the other. This fixes a wrong implementation of minPeakDelta when mode="p" or "v"
  * new function "lowpass" using actual engineering rules to set filter
  * c.DyadExperiment has been relaxed to allow different s1 and s2 names
  * WARNING: rIP_utilities is now a hot flaming mess!!
    *  I have introduced the concept of "flex" in the windowing procedures. "flex" means that instead of
       removing the first and last half windows, initial and ending parts are processed with windows of 
       decreasing size
    *  this has broken at least nwin, winInter, and the new functions approxbywin and byWin

  
## v.1.0.0.9011
#### 2021/08/03
  * utility function nwin() added

## v.1.0.0.9010
#### 2021/07/05
  * minor bug fixes regarding NAs and signals that aren't skin conductance


## v.1.0.0.9009
#### 2021/05/17
  * scaledCorrelation (off by default)
  * weird start end bugs again....
  
## v.1.0.0.9008
#### 2021/03/24
  * bugfixes

## v.1.0.0.9007
#### 2021/03/23
  * modified peakFinder() function to avoid detecting micro-peaks in generally flat areas. This vastly improves the AMICo performance (less false positives). This sets a change to AMICo version v1.1

## v.1.0.0.9006
#### 2020/12/30
  * bug fixes

## v.1.0.0.9005
#### 2020/12/28
  * implemented new artefacts system, any trace of "valid" and "time" has been purged
  * removed duration attributes
  * new xstart, xend, xduration, functions which report correct start and end in time units
  * catExtractLong renamed in extractEpochs
  * removed graphical information from dyadstream

## v.1.0.0.9004
#### 2020/12/18
  * pmBest refactor, more elegant code
  * groupId get functions

## v.1.0.0.9003
#### 2020/09/10
  * Improved documentation
  * improved SignalFilter 
  * DyadSignal constructor no more includes a time and valid object in view of specifying artefacts with start-end files
  * new functions: window.DyadSignal


## v.1.0.0.9002
  * package renamed to DyadSync

## v.1.0.0.9001


#### 2019/06/13

  * included 'c' function for Dyad Objects
  * substituted many warnings with messages
  * various bugfixes


#### 2018/12/18
Questa versione è ad uno stato di sviluppo instabile.

  * aggiunto rIP_extract_dev.R: instead of getting a summary(e.g. median) for each occurrence of an epoch (or category), first pastes together the stream correspoding to each epoch and THEN calculates the summarizing function.
  * aggiunta una guida a rIP extract (readme.txt)
  * setArtefacts adesso seleziona la seduta corretta e salva gli artefatti come tabella di epoche. Il dyadStream logico "valid" viene ancora salvato per compatibilità ma è deprecato.
  * aggiunto argomento "na.rm" a cohend()
  * aggiunta utility di case conversion totitle()

#### 2018/10/24
Questa versione è ad uno stato di sviluppo instabile, ma PMBest (lagSec=7,match_threshold=0.5,algorithm = "dev") discrimina PS da non PS.

  * unificati ccfBest e ccfBestSlope con parametro per slope e MA
  * un sacco di immondizia su PMBest. ma fondamentale ritorno alle correlazioni sul segnale e non sulle slope!
  * abilitate le funzioni di Extract ai diversi outputName e non solo PMBest e CCFBest
  * dal momento che outputName: deprecata la var globale SYNC_CLASSES, eliminata hasSync
  * aggiunto argomento pres.sign a rangeRescale. Quando la scala deve preservare i segni.

#### 2018/10/17
Questa versione è ad uno stato di sviluppo instabile, ma per avere un punto di backup.

#####Sync_CCFBest.R
  * eliminato il warning sui 5 secondi di lag
  * aggiunto il parametro "outputName" per salvare diversi CCFBest nello stesso DyadSignal
  * aggiunto kleinbubIndex session index, in alternativa a Marci Concordance
  * aggiunta ccfBestSlope, come ccfBest, ma fa le correlazioni sullo slope. Non bastava aggiungere un parametro?
  
#####Sync_PMBest.R
  * pmBest, aggiunto il parametro "algorithm" per specificare il tipo di ppSync, classico, "dev", o sloped cross correlations
    * dev: ogni sequenza picco-valle di s1 e s2 è stretchata alla stessa lunghezza (durata)
    * sccf (o wccs): PM trova la sequenza di best lag, poi la solita windowed CC sulle slope, applicando per ogni finestra la lag corrispondente
  * aggiunto il parametro "outputName" per salvare diversi CCFBest nello stesso DyadSignal
  
#####classes.R
  * sampRate() deprecato. è un clone di frequency() che è stato esteso agli oggetti Dyad...
  * aggiunto as.ts.DyadStream come fix di diff.ts(). Potrebbe avere conseguenze.
  
#####filters.R
  * **IMPORTANTE:** cambiato sostanzialmente l'approccio ai filtri. La funzione filtro deve essere più semplice possibile, e funzionare su un solo vettore. Altre funzioni poi devono occuparsi di applicare il filtro base ad oggetti complessi:
    * expApply() deprecato. Può essere utile in alcune situazioni, ma forse meglio estendere lapply.DyadExperiment
    * signalFilter() applica una funzione (filtro) su s1 e s2 in oggetti Dyad....
    * movAv() non è più un metodo generico
    
#####random.R
  * diversi export di funzioni
  * aggiornamenti dal vecchio DyadClass a rIP
  * nuovo approccio a dyadComb()
  
---------------------------------------

#### 2018/07/19
* bugfixes in catExtract.DyadExperiment

#### 2018/07/15
* catApply.DyadSession ora permette output multipli
* aggiunta cloneAttr per fare copia di classAttr in un solo comando, versione generale di cloneDyadStream
* bug fixes on catApply and timeMaster and IO functions

#### 2018/07/15
* bugfixes a catApply()
* NEW: catExtract() funzione che estrae da un DyadExperiment tutte le categorie di un tipo, e aggrega secondo i parametri specificati
* trasnsizione dal concetto di catSummary al concetto di "extract"
  * dovrebbe trasformarsi in un generico "epoching" più in là
* Nuova funzione streamExtract()!!!

#### 2018/07/14
* migliorie a PMBest: aggiunti un threshold minimo per i match, e una durata minima per le finestre di sincronizzazione.
* PMBest testato accuratamente (restano solo alcuni dubbi sulla procedura di sync, cfr. todo)
* readDyadExperiment scorporato in IOgeneric() che si occupa di tutti i lavori di manipolazione file, e readDyadSignal() e readDyadCategory() che fanno cose specifiche per segnali numerici o tabelle categoriali.
* introdotta catApply() funzione generica per eseguire una funzione su ciascuna finestra categoriale
* CCFBest reso compatibile con "class structure v3" e testato
* migliorie a window.DyadStream() che ora supporta anche duration
* migliorie a 'classAttr<-' che ora non sovrascrive 'tsp' se presente anche nel oggetto di destinazione

#### 2018/07/11
* NAartifacts renamed to setArtefacts
* setArtefacts working with v3
* added $time component to DyadSignals
* fixed aliases in rIP_get.R

#### 2018/07/10
* flexMA è un metodo S3 generale
* classAttr permette di estrarre e copiare attributes in modo sicuro
* PMBest testato. Aggiunto un threshold per accettare i match p-p v-v. Un buon valore sembra 0.7


#### 2018/07/09 18:47
* PMBest completamente compatibile con la v3

#### 2018/07/08 15:56 "class structure v3"

* sostituito con c() i vecchi experimentMerge
* ho tolto signals e categ da DyadSession!!!! non aveva particolarmente senso tenere session\$signals e session\$category allo stesso livello, visto che non ci sono analisi solo categoriali (per definizione di IP), ha più senso considerare categ come un tipo speciale di signal, e risparmiare un livello. Es: invece di session\$signals\$SC --> session\$SC
* ho cambiato la struttura delle analisi ccf nella classe, per renderela più astratta e generalizzabile. Ora c'è una classe CCFBest e PMBest per tenere i risultati delle analisi. Ciascuno contiene un vettore sync, uno lag, una tabella table con vari calcoli, e attributi con i settings. 
* ho tolto tutti i metadata dalle liste e le ho messe negli attributes, 

---------------------------------------

#### initial changes

* cambiato patient therapist con s1 s2
* readDyad ora accetta start, end o duration
* la gestione degli artefatti ora è non-distruttiva (ma va implementata in ogni analisi)