---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "tools/readme/README-"
)
```

# rIP
an R package for Interpersonal Physiology, and other dyadic synchronization analyses.

### Overview
The package contains a broad set of functions to import, filter, analyze, and plot continuous data stemming from dyadic interactions. A typical application is to analyze the synchronization between the continuous physiological activity of patient and therapist across one or more sessions. The flexible class system allows to represent most type of designs, longitudinal or cross-sectional.

The documentation is work in progress, and is organized through different vignettes.

####complete vignettes:
* [AMICo algorithm](vignettes/amico.html)

####future vignettes:
* class system
* Comparison between different signals
* Synchrony within specific epochs, or time markers