---
title: "TODO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# ULTRA IMPORTANT KNOWLEDGE
  * puoi debuggare gli argomenti missing e le chiamate stampando:
  __print(match.call())__
  * puoi salvare tutti i parametri con:
  __c(as.list(environment()), list(...))__
  * marker nel codice:
    * @TSBUG
      * cerca tss tse ts start end startend sampRate( tsp DyadStream xstart xend
    * @OBSOLETE
    * @HACK cose brutte da sistemare quando hai tempo


## NEXT STEPS & CRITICAL BUGS
  * crea algoritmo SCoPhaRSi Skin Conductance Phasic Response Similiarity
    
  * amico2 ha dei buchi weight linea 863 prova mean [maybe done]
  * interval_sec diventa maxSize e con minSize devono essere implementati anche
    nella prima parte con i picchi veri. NB cè gia maxPeakDuration
  * peakfinder trova amp negative
  * Alcuni nomi di dyadcategory causano errori come "SD"
  * tutto il sistema di permutazioni non permette di analizzare dati per i quali non ci siano osservazioni (nrow = 0)
  * in ppSync_dev perchè usare la lunghezza del più corto per interpolare? Usa già
    quella finale dell'interpolazione.
  * rinomina winSec in WIN e incSec in INC
  * rinomina SR o sampRate in frequency
  * ccfBest dovrebbe usare byWin

## Git

## AMICO2
  * gli artefatti sono rimossi da sync e lag ma non da xbest.
  * amico 2 causa permutation tests tutte negative :-O
   
## physiology
  * recupera tutte le funzioni avanzate sviluppate per VRperGenere
  
## videoFrame
  * il sistema  IN TEORIA è robusto con la visualizzazione di 2 segnali, ma non è testato
  * in particolare non è robusto per la visualizzazione di algoritmi di sync diversi da AMICo1
  *
  
## mechanics
  * ottimizza ccfBest e omologa l'output di ccfBest e pmBest. In particolar modo 
    ci sia il tempo per le finestre di ccfBest
  * fai una nuova funzione: filterArtefacts() che applica una FUN sulle finestre specificate da setArtefacts(), ad es settando a NA, o smoothando. Metti anche come filtro una possibile label per scriminare diversi artefatti. flat, wiggle, motion, etc.
  * winInter, and  approxbywin dovrebbero usare byWin?



## minor BUGS & various mishaps
 * cloneAttr e classAttr cambiano solo alcuni attributi, ha senso?
   usando peraltro una variabile globale LOCK_ATTR. 
   Forse in R internals c'è una guida per dire come fare meglio?

## rats CLASS 
  * implementa summary.rats con tables per rats non numerici
  * implementa plot.rats
  * print.rats è un po' frustrante
  * rescaleByWin non salva i metadati es. timeUnit
  * metti error se period = 1 o frequency = 1




## Permutations
  * implementa misure di effect size robuste per le permutations:
    https://garstats.wordpress.com/2016/05/02/robust-effect-sizes-for-2-independent-groups/
  * se usi from=remaining, fullFrom è una cosa strana, con tagli e buchi. controlla.
    eventualmente incolla i pezzi con crossfade.
    full_from = do.call(c,ex2$remaining)
    full_from[!is.na(full_from)]
    full_from = full_from[!is.na(full_from)]
    plot(full_from, t="l")


    
## Category extraction
  * (forse fatto?) se voglio usare più di un groupIndex, ad es IM_tipo e IM_livello, queste si sovrascrivono in epochStream. Devi sempre indicare signal="SC", sync="PMdev",streamKey = "sync", category="IM",groupIndex="micro". 
  * DyadCategory to stream (category, column) : crea versione interpolata. utile principalmente solo per plottare
  * byCat(signal, category, stream=c(patient, therapist, bestCCF, bestLag,lag0), FUN) : applica una funzione es la media ai diversi livelli del factor di uno stream. a seconda che input sia experiment, session o singal applica adeguatamente.


## Graphics 
  * scrivi funzioni generiche per long plot, e per videoframesync

  
## double check & cleanup
  * setArtefacts richiede che dyad sia char con leading zero. tipo "01" funziona invece 1L no.
  * sccf sarebbe meglio wccs "window cross corr of slopes"
  * aggiungi '...' a PMBest e CCFBest, per accomodare i parametri di eventuali altri algoritmi di calcolo.
  * elimina i commenti e le cose obsolete. Sto segnando con @OBSOLETE le parti da rimuovere e/o spostare in obsolenscence.R
  * controlla gli argomenti missing nelle funzioni parallelizzate. In particolare
    AMICo, e filter
  * pulisci rats da molti commenti

    
  
  

## Performance
  * usa il profiler per trovare bottlenecks: https://support.rstudio.com/hc/en-us/articles/218221837-Profiling-R-code-with-the-RStudio-IDE
   


## Backlog
  * in xbest di AMICo v1.1  ci sono delle (rare) occorrenze in cui lo stesso picco viene usato 2 volte, che è grave.
  * errori (rari) in PMBest (su diadi random): 
    * In cor(rs1, rs2, use = "c") : la deviazione standard è zero
    * In s2p\$bool + s2v\$bool :  longer object length is not a multiple of shorter object length
  * tempo in millesimi e/o frazioni di secondo in timemaster



### low priority
#### DyadExperiment
* quando crei experiment fai tutti i check di coerenza interna e magari salva esplicitamente il tipo di disegno, longitudinale, gruppi, misto
  * soprattutto gli stessi s1 e s2 names, altrimenti rischi di fare grossa confusione
* trova un modo per implementare i bei plot di PMBest  
* controlla che dyadComb.DyadExperiment funzioni dopo la rimozione di $signals
* rotating or 0-100 progress bar in nested funcstions
* '[.DyadExperiment' e session, signal e stream, copiano anche gli attributi
* controlla che tutti i segnali abbiano lo stesso dyadID e s1 s2 names
